Blinker light task
lhr-solar/Controls pull request #135
Opened 2021-03-06 22:03 UTC by ErickCortez98

Implemented BlinkLights task which is spawned by the ReadSwitches

2021-03-06 22:25 UTC, JimothyGreene requested changes
Just a few small changes. Also, to keep our PRs small, make sure that you branch off of `master` so that changes from another unmerged branch don't pop up in this PR. Just a note for future

2021-03-06 22:25 UTC, JimothyGreene commented on Apps/Inc/BlinkerLight.h
> +void Task_BlinkLight(void *p_arg);
This is already defined in `Tasks.h`

2021-03-06 22:25 UTC, JimothyGreene commented on Apps/Src/BlinkerLight.c
> +    while(true){
I would just make this a `while (1)` for consistency's sake

2021-03-06 22:25 UTC, JimothyGreene commented on Apps/Src/BlinkerLight.c
> +        }
Logic seems good to me

2021-03-13 22:03 UTC, Cam0Cow submitted a review, later dismissed

2021-03-20 15:41 UTC, JimothyGreene requested changes
Looks good for the most part. Make sure you're passing in the global car state to all the tasks, otherwise they'll run into some null pointer issues. Also, I wouldn't merge this in until the ReadSwitches task has been merged in as well. Without that working, we can't fully test this.

2021-03-20 15:41 UTC, JimothyGreene commented on Tests/Test_BlinkerLight.c
> +    );
It doesn't seem like you're passing in the global car state struct anywhere. Is it declared at all anywhere?

2021-12-29 06:09 UTC, babusid commented
I think the newer BlinkLights PR #168 may be more suitable as it's just a bit more current. That one is in line with some planned updates to the car state struct that I don't think this one has. @Cam0Cow do you have any additional insight? I'm going to close this for now, and we can open it back up if we need to.

2021-12-29 06:09 UTC, closed without merging