Rtos/read car can
lhr-solar/Controls pull request #140
Opened 2021-03-27 21:22 UTC by Cam0Cow

2021-03-27 21:53 UTC, babusid commented
CANBus_Read may have to be changed on a driver level to use a mutex lock to make sure that only one read happens at a time.

2021-04-03 19:19 UTC, JimothyGreene requested changes

2021-04-03 19:19 UTC, JimothyGreene commented on Apps/Src/ReadCarCAN.c
> +        if (CANbus_Read(buffer) == SUCCESS && (++faultCounter == THRESHOLD)) {
Also need to check what the actual message is. BPS will send either a 0 (charging disabled) or a 1 (charging enabled). If charging is disabled, we need to disconnect the contactors. If BPS is sending a 1, we don't need to change anything about the connections

2021-04-03 19:19 UTC, JimothyGreene commented on Apps/Src/ReadCarCAN.c
> +        if (CANbus_Read(buffer) == SUCCESS && (++faultCounter == THRESHOLD)) {
Also, the threshold isn't really needed here. You should use the threshold to check if the message was received at all (i.e.) if `CANbus_Read` returns ERROR, that means BPS hasn't sent the message. If that happens THRESHOLD times, we should disconnect.

2021-04-03 21:21 UTC, JimothyGreene requested changes

2021-04-03 21:21 UTC, JimothyGreene commented on Apps/Src/ReadCarCAN.c
> +            car->IsRegenBrakingAllowed = ON;
I would say this should default to off if we're not receiving a message from BPS saying it's safe to have it on.

2021-04-10 16:35 UTC, JimothyGreene requested changes
Looks mostly good. Just one change on the test file to accommodate for the design change

2021-04-10 16:35 UTC, JimothyGreene commented on Tests/Test_ReadCarCAN.c
> +    OSTaskDel(NULL, &err);
Can you change this to reflect the new operation?

2021-04-10 19:29 UTC, JimothyGreene approved these changes

2021-04-10 19:54 UTC, merged