SendCarCan Additional Info
lhr-solar/Controls pull request #268
Opened 2022-10-22 19:12 UTC by NathanielDelgado

Send pedal, switch, lights, and contactor readings on the CAN line for telemetry to use

2022-10-22 19:38 UTC, IshDeshpa reviewed
Very minor changes

2022-10-22 19:38 UTC, IshDeshpa commented on Apps/Src/SendCarCAN.c
> +}DATAMSG_t;
```suggestion
typedef union CarData_t{
    struct{
        uint64_t accelPedal : 8;
        uint64_t brakePedal : 8;
        uint64_t switchBitmap : 16;
        uint64_t lightBitmap : 8;
        uint64_t contactorBitmap : 8;
        uint64_t reserved : 16;
    };
    uint64_t val;
}CarData_t;
```

2022-10-22 19:38 UTC, IshDeshpa commented on Apps/Src/SendCarCAN.c
> +    CANMSG_t carMSG;
Rename to motorMsg and carMsg

2022-10-22 19:38 UTC, IshDeshpa commented on Apps/Src/SendCarCAN.c
> +            bool switchState = (bool)Switches_Read(i);
Casting States to bools is technically unsafe. Use a ternary:
`Switches_Read(i)==ON?true:false`

2022-10-22 19:38 UTC, IshDeshpa commented on Drivers/Inc/Minions.h
> +     NUM_SWITCHES,
I'm not a huge fan of this, I would rather use a macro for NUM_SWITCHES, but it's fine if nobody else has a problem with it.

2022-10-22 19:38 UTC, IshDeshpa commented on Apps/Src/SendCarCAN.c
> +#include "common.h"
File header documentation

2022-10-22 19:38 UTC, IshDeshpa commented on Apps/Src/SendCarCAN.c
> +    CANMSG_t motorMSG;
Method documentation

2022-11-12 21:27 UTC, NathanielDelgado commented
I need to make sure the bitmaps are zero before updating them again (would hold old data).

2022-12-01 03:19 UTC, babusid requested changes
Overall, looks solid to me. Just change the struct thing, so that we don't have an unnecessarily complex data structure. Pointers cast + dereference is cleaner in my opinion because it only exists where it needs to exist. You could even break it out into a helper "conversion" function if you think that's cleaner.

2022-12-04 00:04 UTC, Cam0Cow approved these changes

2022-12-04 00:05 UTC, merged