Update PR templates
lhr-solar/Controls pull request #356
Opened 2023-09-23 19:23 UTC by Cam0Cow

2023-09-23 20:55 UTC, IshDeshpa requested changes

2023-09-23 20:55 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
Test has been tested on hardware

2023-09-24 23:48 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Tested on hardware
```suggestion
- [ ] Tests have passed on hardware
```

2023-09-24 23:49 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Software feature has documentation for it updated
```suggestion
- [ ] Software feature has documentation for it updated in both ReadTheDocs and the code
```

2023-09-24 23:50 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Followed Coding Style Guide
```suggestion
- [ ] Followed Coding Style Guide 
- [ ] Presented/discussed in some capacity with others on the Controls team
```

2023-09-25 21:04 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] Did you have fun?
```suggestion
- [ ] Tagged appropriate issue ticket on this PR
- [ ] Did you have fun?
```

2023-09-26 18:12 UTC, Arnav-Surjan requested changes
Everything looks good aside from the changes I suggested.

2023-09-26 18:12 UTC, Arnav-Surjan commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] If applicable, have you added the new feature to main.c
```suggestion
- [ ] If applicable, have you added the new feature to main.c?
```
Add question mark.

2023-09-26 18:24 UTC, IshDeshpa commented on PULL_REQUEST_TEMPLATE.md
> +- NOTE: If test file already exists, use that one
"Testing" perhaps?

2023-09-26 18:39 UTC, IshDeshpa submitted a review, later dismissed

2023-09-26 22:49 UTC, IshDeshpa commented on .github/ISSUE_TEMPLATE/bug_report.md
> +6. What does the error look like?
```suggestion
6. What does the error look like?
7. Does this issue already exist?
```

2023-09-26 22:50 UTC, IshDeshpa commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of what the problem is.
```suggestion
A clear and concise description of what the problem is. Please make sure the issue for this feature does not already exist.
```

2023-09-26 22:50 UTC, NathanielDelgado approved these changes
lgtm

2023-09-26 23:00 UTC, NathanielDelgado approved these changes
Really good work team!

2023-09-26 23:04 UTC, IshDeshpa approved these changes
LGTM 💅💅💅💅

2023-09-26 23:05 UTC, NathanielDelgado approved these changes
Love to see it!♥

2023-09-26 23:06 UTC, merged