Lights simulation: Fixes #32
lhr-solar/Controls pull request #46
Opened 2020-09-12 18:50 UTC by babusid

- Created Lights.C which has Read and Update functions for all Lights.
- Created Lights.H which exposes Lights.C to the main simulator.
- Wrote Test file for Lights which switches all lights on and off on a loop and prints it to the console.
- Updated simulate.py and lights.py to include all ten lights built into the Lights C module.

2020-09-16 04:02 UTC, Cam0Cow requested changes

2020-09-16 04:02 UTC, Cam0Cow commented on Tests/Test_BSP_Lights.c
> +        printf("%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\r",
The values aren't lined up under their respective labels, they should probably be more spaced out.

2020-09-16 04:25 UTC, JimothyGreene requested changes
One main functionality change. See in line comments.

2020-09-16 04:25 UTC, JimothyGreene commented on BSP/Inc/BSP_Lights.h
> +void BSP_Lights_Switch(LIGHT_t LightChannel);
We don't always want to toggle the light, so I would make this function called `BSP_Lights_Set()` and also take in a `state_t` parameter. That way we don't need to know whether or not the lights are on to turn them on or off to turn them off. Mainly it'll just relieve us of one step in the application layer.

2020-09-16 04:25 UTC, JimothyGreene commented on BSP/Simulator/Src/BSP_Lights.c
> +void BSP_Lights_Switch(LIGHT_t LightChannel){
See comments in header file

2020-09-19 17:17 UTC, ErickCortez98 requested changes
Small details, see comments.

2020-09-19 17:17 UTC, ErickCortez98 commented on BSP/Simulator/Src/BSP_Lights.c
> +        return 2;
Returning value inside a void function. 
```suggestion
        return;
```

2020-09-26 19:45 UTC, JimothyGreene approved these changes
Looks all good

2020-09-26 19:46 UTC, merged