Fix style
lhr-solar/Controls pull request #67
Opened 2020-10-10 18:55 UTC by SoroushF79

Very minor style fixes

2020-10-17 14:38 UTC, JimothyGreene requested changes
PEP8 standards want 2 blank lines between each function in Python

2020-10-17 21:15 UTC, JimothyGreene requested changes
Few minor changes

2020-10-17 21:15 UTC, JimothyGreene commented on Drivers/Src/CANbus.c.save
> +#include "CANbus.h"
I'm not really sure what this file is, but we shouldn't track this with git

2020-10-17 21:15 UTC, JimothyGreene commented on BSP/Simulator/Src/BSP_CAN.c
> +            else {
I'd prefer if else statements to be written like:

```
if (condition) {
// body
} else {
// body
}

2020-11-07 16:27 UTC, JimothyGreene requested changes
Looks good. Just merge `master` into this and double-check the new `MotorController.py` file since now it's been refactored.

2020-11-07 17:13 UTC, JimothyGreene requested changes

2020-11-07 17:13 UTC, JimothyGreene commented on BSP/Simulator/Hardware/MotorController.py
> +
Remove the parts of this that are encapsulated in the CarState class

2020-11-07 19:49 UTC, ErickCortez98 submitted a review, later dismissed

2020-11-07 20:26 UTC, JimothyGreene submitted a review, later dismissed

2020-11-07 20:35 UTC, merged