Ale cur vel fix
lhr-solar/Controls pull request #79
Opened 2020-10-17 19:43 UTC by AleNeff

Switched placement of current bits and velocity bits for csv file to be read correctly by simulator

2020-10-17 21:09 UTC, JimothyGreene requested changes
Overall, this doesn't seem like it switched anything. You may have switched them and then switched back? I'm not sure. All I'm seeing is that you removed the incrementing of the `index` variable.

2020-10-17 21:21 UTC, AleNeff commented
Yeah I think I accidentally reverted the change, newest commit & push fixed it.

2020-10-17 21:32 UTC, JimothyGreene approved these changes
Looks good to me. Should follow the correct format now.

2020-10-18 03:39 UTC, Cam0Cow approved these changes

2020-10-23 17:46 UTC, merged