GPIO Precharge
lhr-solar/Controls pull request #91
Opened 2020-11-21 20:25 UTC by SoroushF79

Layer Precharge on currently unwritten GPIO functions

2020-11-21 20:42 UTC, JimothyGreene requested changes
Few minor changes for this prototyped version

2020-11-21 20:42 UTC, JimothyGreene commented on BSP/Simulator/Hardware/PreCharge.py
> +
There won't be a `GPIO.py`, so this write function should write the data to the correct line of the `GPIO.csv` itself

2020-11-21 20:42 UTC, JimothyGreene commented on BSP/Simulator/Src/BSP_Precharge.c
> +    int data = BSP_GPIO_Read();
You'll end up passing in a parameter here. It'll probably be an enum, so don't worry about it for now. Just a heads up

2020-12-04 02:03 UTC, ErickCortez98 requested changes

2020-12-04 02:03 UTC, ErickCortez98 commented on Drivers/Src/Precharge.c
> +#define MOTOR_BIT 3
These could be part of the header file

2020-12-19 19:18 UTC, JimothyGreene requested changes
The Python simulation side doesn't read from the correct port (line) in the GPIO.csv file. It should be reading from line 3 (port C). Also, we don't need a write function since we'll never change the state of the precharge boards from the simulator. I would take a look at the Contactors code that was merged into master recently. It should be nearly identical on both the Python and C sides.

2020-12-19 20:43 UTC, JimothyGreene approved these changes
All working!

2020-12-19 21:08 UTC, ErickCortez98 approved these changes

2020-12-19 21:39 UTC, merged